version: '3.8'

services:
  server-guard:
    container_name: server-guard-shutdown
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always