IMAGE_DENIED = 'https://cdn.gilcdn.com/asset/GenericMessages/denied.png'
IMAGE_DEFAULT_AVATAR = 'https://cdn.gilcdn.com/asset/Default/Gil-md.png'
IMAGE_SUB_COPPER = 'https://cdn.gilcdn.com/asset/ServerSubscriptions/fancy_copper_128x128.png'
IMAGE_SUB_SILVER = 'https://cdn.gilcdn.com/asset/ServerSubscriptions/fancy_silver_128x128.png'
IMAGE_SUB_GOLD = 'https://cdn.gilcdn.com/asset/ServerSubscriptions/fancy_gold_128x128.png'
IMAGE_GIL_THUMBS_UP = 'https://cdn.gilcdn.com/asset/Emojis/Custom/thumbsup.webp'
IMAGE_BOT_LOGO = 'https://cdn.gilcdn.com/CustomReaction/2493526bcc0f8d23613884a7224a91dc-Full.webp'
IMAGES_NOT_FOUND = 'https://cdn.gilcdn.com/asset/GenericMessages/not-found.png'
